steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - webhook
  - --region=us-west1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated
  - --entry-point=mutate
